# version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./MJv1BE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:rootpassword@db:3306/appdb"

  frontend:
    build:
      context: ./MJv1FE
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data: