# Generated by Django 5.1.7 on 2025-03-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cno', models.CharField(db_column='Cno', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CName', max_length=100)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='Gender', max_length=20)),
                ('mobile', models.CharField(db_column='Mobile', max_length=20)),
                ('roomNo', models.CharField(db_column='RoomNo', max_length=20)),
                ('checkInTime', models.DateTimeField(db_column='CheckInTime')),
                ('checkOutTime', models.DateTimeField(db_column='CheckOutTime', null=True)),
                ('resideTimePeriod', models.CharField(db_column='resideTimePeriod', max_length=100)),
                ('idCardNo', models.CharField(db_column='IDCardNo', max_length=20)),
                ('image', models.CharField(db_column='Image', max_length=100, null=True)),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNo', models.CharField(db_column='RoomNo', max_length=20, primary_key=True, serialize=False)),
                ('roomAmount', models.DecimalField(db_column='RoomAmount', decimal_places=2, max_digits=10)),
                ('durationType', models.CharField(db_column='DurationType', max_length=20, null=True)),
                ('roomType', models.CharField(db_column='RoomType', max_length=20, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': True,
            },
        ),
    ]
