# Generated by Django 5.1.7 on 2025-04-28 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='房间号')),
                ('room_status', models.CharField(choices=[('vacant', '空闲'), ('occupied', '已入住'), ('maintenance', '维护中'), ('reserved', '已预订'), ('cleaning', '清洁中'), ('locked', '锁定'), ('unavailable', '不可用')], default='vacant', max_length=20, verbose_name='房间状态')),
                ('room_type', models.CharField(max_length=50, verbose_name='房间类型')),
                ('room_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='房间金额')),
                ('duration_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='租住时间单位')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
            ],
            options={
                'verbose_name': '房间配置项',
                'verbose_name_plural': '房间配置项',
                'db_table': 'room_config',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cno', models.CharField(db_column='Cno', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CName', max_length=100)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='Gender', max_length=20)),
                ('mobile', models.CharField(db_column='Mobile', max_length=20)),
                ('checkInTime', models.DateTimeField(db_column='CheckInTime')),
                ('checkOutTime', models.DateTimeField(db_column='CheckOutTime', null=True)),
                ('resideTimePeriod', models.CharField(db_column='resideTimePeriod', max_length=100)),
                ('idCardNo', models.CharField(db_column='IDCardNo', max_length=20)),
                ('image', models.CharField(db_column='Image', max_length=100, null=True)),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('已预订', '已预订'), ('已入住', '已入住'), ('已退宿', '已退宿'), ('未知', '未知')], db_column='Status', default='未知', max_length=20)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='apartment.room')),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_config',
            field=models.ManyToManyField(related_name='rooms', to='apartment.roomconfig', verbose_name='房间配置'),
        ),
    ]
