# Generated by Django 5.1.1 on 2024-10-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkOutTime',
            field=models.DateTimeField(db_column='CheckOutTime', null=True),
        ),
    ]
